language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 0jbXdxGTD8tLCuNew4bwgULbP2imf12DHEH/LBrTjraQbMlgQPNmx1XevI0Nd8RJPjVqq6kpZJxolLwuX+kPtd3h6ZILP0qYD0VIIY/8ZHnChu9geBPatFHAojqwpIslUHMgdBPtw/lf1DGieVIjwCnGlUD679VZ06CQb6Wt3RloVplX93bUiU+xBWIcOhzYx5SJqTGHNfAEs9E625YYxDrKrkOMtC0lVXrN2azKCRwWcWSAcWPtZE6yTvvfkkSfGAYxcwNIekBMVrtTqfQ5ezwBkiO22s29lXImeEyGI37kfphkctSSEyfwsp205epjkcHwI0sSL+AjJWQ4A+pAFI8+QI1hQ6MobCSjaLREAEHdZuYjskWeITmuZfC1EyJMZ5nFgAIu9H/aPio7xMMEp3fEEuzCryNvoCFHmNMcvrc7gy/NvP/WGkaaUlzB9v/j/Bcq1JyI0HIDTpNfYtbzxFKaBMOiwCXgJ38soSvaH6hh00i7ML9kMusoWGgBZgg5rcW9MHnFEw2KaY7YccEZxWZPm22mqm4VNdAumj7amDLpWS85x5tz+ykJVbXI6CM7R6HUC8tQAMiC0u6cvxHIpXCSnrN5IIKJBadNd9QbB8SwqjXu4Z8XOwomxNS9KhWklHslGrgdsaS1rckI2ih3NBYP6vFjIi6nceYOMKM32cU=
  app: fathomless-sands-63376
  on:
    repo: SeanCodyDev/mydailyjournal-api
